// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
config({ path: ".env.local" });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations / db push use the session pooler (port 5432, IPv4). DIRECT_URL
    // falls back to DATABASE_URL for local dev if unset.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
