export type Restaurant = {
  name: string
  venueId: number | null
  neighborhood: string
  cuisine: string
  daysOut: number
  releaseTime: string | null // HH:MM ET, 24h
  releaseNotes: string
  priceRange: string
}

export const NYC_RESTAURANTS: Restaurant[] = [
  {
    name: "Carbone",
    venueId: 1505,
    neighborhood: "Greenwich Village",
    cuisine: "Italian-American",
    daysOut: 28,
    releaseTime: "00:00",
    releaseNotes: "Drops at midnight ET exactly 28 days out. One of the hardest tables in NYC — gone in seconds.",
    priceRange: "$$$$",
  },
  {
    name: "Lilia",
    venueId: 1274,
    neighborhood: "Williamsburg",
    cuisine: "Italian",
    daysOut: 28,
    releaseTime: "00:00",
    releaseNotes: "Midnight drop 28 days out. Notoriously difficult.",
    priceRange: "$$$",
  },
  {
    name: "4 Charles Prime Rib",
    venueId: 1546,
    neighborhood: "West Village",
    cuisine: "Steakhouse",
    daysOut: 28,
    releaseTime: "00:00",
    releaseNotes: "Midnight ET 28 days out. ~30 seats — one of the most competitive bookings in NYC.",
    priceRange: "$$$$",
  },
  {
    name: "Rezdôra",
    venueId: 8585,
    neighborhood: "Flatiron",
    cuisine: "Northern Italian",
    daysOut: 28,
    releaseTime: "00:00",
    releaseNotes: "Midnight drop 28 days out. Very competitive pasta-focused restaurant.",
    priceRange: "$$$",
  },
  {
    name: "Atomix",
    venueId: 6509,
    neighborhood: "Midtown",
    cuisine: "Modern Korean",
    daysOut: 60,
    releaseTime: "10:00",
    releaseNotes: "2-Michelin-star. Opens ~60 days out at 10am ET. Tasting menu only.",
    priceRange: "$$$$",
  },
  {
    name: "Jua",
    venueId: 11322,
    neighborhood: "Flatiron",
    cuisine: "Modern Korean",
    daysOut: 28,
    releaseTime: "00:00",
    releaseNotes: "Midnight drop 28 days out. Michelin-starred tasting menu.",
    priceRange: "$$$$",
  },
  {
    name: "Torrisi",
    venueId: 68889,
    neighborhood: "SoHo",
    cuisine: "Italian-American",
    daysOut: 28,
    releaseTime: "00:00",
    releaseNotes: "Midnight drop 28 days out. Major Rich Torrisi comeback restaurant.",
    priceRange: "$$$$",
  },
  {
    name: "Frenchette",
    venueId: 3258,
    neighborhood: "Tribeca",
    cuisine: "French",
    daysOut: 28,
    releaseTime: "00:00",
    releaseNotes: "Midnight drop 28 days out. James Beard-winning. Bar walk-ins available.",
    priceRange: "$$$",
  },
  {
    name: "Le Bernardin",
    venueId: 124,
    neighborhood: "Midtown West",
    cuisine: "French Seafood",
    daysOut: 28,
    releaseTime: "00:00",
    releaseNotes: "3-Michelin-star. Midnight drop 28 days out. Tasting menu and à la carte.",
    priceRange: "$$$$",
  },
  {
    name: "Laser Wolf",
    venueId: 56547,
    neighborhood: "Williamsburg",
    cuisine: "Israeli Grill",
    daysOut: 28,
    releaseTime: "09:00",
    releaseNotes: "9am ET drop 28 days out. Rooftop. Very popular summer spot.",
    priceRange: "$$$",
  },
  {
    name: "Gage & Tollner",
    venueId: 43620,
    neighborhood: "Downtown Brooklyn",
    cuisine: "American Steakhouse",
    daysOut: 28,
    releaseTime: "00:00",
    releaseNotes: "Midnight drop 28 days out. Historic NYC revival.",
    priceRange: "$$$",
  },
  {
    name: "Gramercy Tavern",
    venueId: 118,
    neighborhood: "Gramercy",
    cuisine: "American",
    daysOut: 28,
    releaseTime: "09:00",
    releaseNotes: "USHG group — 9am drop. Tavern room walk-ins available. Dining room books 28 days out.",
    priceRange: "$$$",
  },
  {
    name: "Eleven Madison Park",
    venueId: 94,
    neighborhood: "Flatiron",
    cuisine: "Modern American (Plant-based)",
    daysOut: 60,
    releaseTime: "09:00",
    releaseNotes: "3-Michelin-star. Opens ~60 days out at 9am. Tasting menu only. $365+/person.",
    priceRange: "$$$$",
  },
  {
    name: "The Grill",
    venueId: 5234,
    neighborhood: "Midtown East",
    cuisine: "American Continental",
    daysOut: 28,
    releaseTime: "00:00",
    releaseNotes: "Midnight drop 28 days out. Four Seasons room revival. Power dining.",
    priceRange: "$$$$",
  },
  {
    name: "Nobu",
    venueId: 126,
    neighborhood: "Tribeca",
    cuisine: "Japanese-Peruvian",
    daysOut: 28,
    releaseTime: "00:00",
    releaseNotes: "Midnight drop 28 days out. Large room — more available than most.",
    priceRange: "$$$$",
  },
  {
    name: "Balthazar",
    venueId: 276,
    neighborhood: "SoHo",
    cuisine: "French Brasserie",
    daysOut: 28,
    releaseTime: "00:00",
    releaseNotes: "Midnight drop 28 days out. Large brasserie — easier to book than boutique spots.",
    priceRange: "$$$",
  },
  {
    name: "Le Coucou",
    venueId: 3153,
    neighborhood: "SoHo",
    cuisine: "French",
    daysOut: 28,
    releaseTime: "00:00",
    releaseNotes: "Midnight drop 28 days out. Daniel Rose's acclaimed French restaurant.",
    priceRange: "$$$$",
  },
  {
    name: "Dirty French",
    venueId: 412,
    neighborhood: "Lower East Side",
    cuisine: "French",
    daysOut: 28,
    releaseTime: "00:00",
    releaseNotes: "Midnight drop 28 days out. Torrisi/Zalaznick group. Easier than Carbone.",
    priceRange: "$$$",
  },
  {
    name: "Crown Shy",
    venueId: 16018,
    neighborhood: "Financial District",
    cuisine: "Modern American",
    daysOut: 28,
    releaseTime: "00:00",
    releaseNotes: "Midnight drop 28 days out. James Kent's Michelin-starred FiDi restaurant.",
    priceRange: "$$$",
  },
  {
    name: "Estela",
    venueId: 1292,
    neighborhood: "Nolita",
    cuisine: "Mediterranean",
    daysOut: 28,
    releaseTime: "00:00",
    releaseNotes: "Midnight drop 28 days out. Bar walk-ins available. Very competitive for dinner.",
    priceRange: "$$$",
  },
  {
    name: "Cosme",
    venueId: 2182,
    neighborhood: "Flatiron",
    cuisine: "Mexican",
    daysOut: 28,
    releaseTime: "00:00",
    releaseNotes: "Midnight drop 28 days out. Enrique Olvera. One of NYC's best Mexican restaurants.",
    priceRange: "$$$$",
  },
  {
    name: "L'Artusi",
    venueId: 432,
    neighborhood: "West Village",
    cuisine: "Italian",
    daysOut: 28,
    releaseTime: "00:00",
    releaseNotes: "Midnight drop 28 days out. Bar seats often available.",
    priceRange: "$$$",
  },
  {
    name: "Daniel",
    venueId: 217,
    neighborhood: "Upper East Side",
    cuisine: "French",
    daysOut: 28,
    releaseTime: "09:00",
    releaseNotes: "2-Michelin-star. Morning release 28 days out.",
    priceRange: "$$$$",
  },
  {
    name: "Jean-Georges",
    venueId: 104,
    neighborhood: "Columbus Circle",
    cuisine: "French-American",
    daysOut: 28,
    releaseTime: "09:00",
    releaseNotes: "3-Michelin-star. Morning release 28 days out.",
    priceRange: "$$$$",
  },
  {
    name: "Ci Siamo",
    venueId: 41823,
    neighborhood: "Hudson Yards",
    cuisine: "Italian",
    daysOut: 28,
    releaseTime: "00:00",
    releaseNotes: "Midnight drop 28 days out. Danny Meyer's Italian restaurant.",
    priceRange: "$$$",
  },
  {
    name: "Momofuku Ko",
    venueId: 95,
    neighborhood: "East Village",
    cuisine: "Modern American",
    daysOut: 7,
    releaseTime: "10:00",
    releaseNotes: "Opens 7 days out at 10am ET. Counter tasting menu. 2 Michelin stars. Shorter booking window.",
    priceRange: "$$$$",
  },
]

export function getRestaurantByVenueId(venueId: number): Restaurant | undefined {
  return NYC_RESTAURANTS.find((r) => r.venueId === venueId)
}

export function suggestSnipeTime(restaurant: Restaurant, targetDate: Date): Date | null {
  if (!restaurant.releaseTime || restaurant.daysOut === 0) return null

  const snipeDate = new Date(targetDate)
  snipeDate.setDate(snipeDate.getDate() - restaurant.daysOut)

  const [hours, minutes] = restaurant.releaseTime.split(":").map(Number)
  // releaseTime is ET — store as UTC offset (ET = UTC-4 in summer, UTC-5 in winter)
  // We store in UTC; the UI shows in ET
  snipeDate.setUTCHours(hours + 4, minutes, 0, 0) // assume EDT (UTC-4) as default

  return snipeDate
}
